/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package framemenu;

import Battle.BattleLogic;
import Battle.MainBattle;
import Pokemones.Lista;
import Pokemones.Pokemon;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Arturo
 */
public class Menu extends javax.swing.JFrame {
    
    Lista listapkmn = BattleLogic.laListap;
    
    private int contador = 0;
    public Pokemon pk1;
    public Pokemon pk2;
    public Pokemon pk3;
    public Pokemon pk4;
    
    
    
     ImagenFondo ejemplo = new ImagenFondo();
    /**
     * Creates new form Menu
     */
    public Menu() {
         
        this.setContentPane(ejemplo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBCharmander = new javax.swing.JButton();
        JBSquirtle = new javax.swing.JButton();
        JBSnorlax = new javax.swing.JButton();
        JBSlugma = new javax.swing.JButton();
        JBArcanine = new javax.swing.JButton();
        JBLapras = new javax.swing.JButton();
        Meowth = new javax.swing.JButton();
        JBMagikarp = new javax.swing.JButton();
        JBEevee = new javax.swing.JButton();
        JLTitle = new javax.swing.JLabel();
        JLWarning = new javax.swing.JLabel();
        JBStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBCharmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/charmander.png"))); // NOI18N
        JBCharmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCharmanderActionPerformed(evt);
            }
        });

        JBSquirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/squirtle.png"))); // NOI18N
        JBSquirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSquirtleActionPerformed(evt);
            }
        });

        JBSnorlax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/snorlax.png"))); // NOI18N
        JBSnorlax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSnorlaxActionPerformed(evt);
            }
        });

        JBSlugma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/slugma.png"))); // NOI18N
        JBSlugma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSlugmaActionPerformed(evt);
            }
        });

        JBArcanine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arcanine.png"))); // NOI18N
        JBArcanine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBArcanineActionPerformed(evt);
            }
        });

        JBLapras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lapras.png"))); // NOI18N
        JBLapras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLaprasActionPerformed(evt);
            }
        });

        Meowth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/meowth.png"))); // NOI18N
        Meowth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeowthActionPerformed(evt);
            }
        });

        JBMagikarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/magikarp.png"))); // NOI18N
        JBMagikarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMagikarpActionPerformed(evt);
            }
        });

        JBEevee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eevee.png"))); // NOI18N
        JBEevee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEeveeActionPerformed(evt);
            }
        });

        JLTitle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLTitle.setText("ELIGE 4 POKEMONES:");

        JBStart.setText("Start");
        JBStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBStart))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JBSlugma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBCharmander, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBArcanine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JBSquirtle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBLapras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBMagikarp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JBSnorlax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBEevee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Meowth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLTitle)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBCharmander)
                        .addGap(12, 12, 12)
                        .addComponent(JBSlugma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBSquirtle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBSnorlax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBLapras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBEevee))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBMagikarp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBArcanine, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Meowth))
                .addGap(28, 28, 28)
                .addComponent(JLWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(JBStart)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCharmanderActionPerformed
        // TODO add your handling code here:
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(2);
                break;
            case 2:
                pk2 = listapkmn.buscar(2);
                break;
            case 3:
                pk3 = listapkmn.buscar(2);
                break;
            case 4:
                pk4 = listapkmn.buscar(2);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }
                
        
    }//GEN-LAST:event_JBCharmanderActionPerformed

    private void JBLaprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLaprasActionPerformed
        // TODO add your handling code here:
        
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(7);
                break;
            case 2:
                pk2 = listapkmn.buscar(7);
                break;
            case 3:
                pk3 = listapkmn.buscar(7);
                break;
            case 4:
                pk4 = listapkmn.buscar(7);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }
        
    }//GEN-LAST:event_JBLaprasActionPerformed

    private void JBSquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSquirtleActionPerformed
        // TODO add your handling code here:
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(1);
                break;
            case 2:
                pk2 = listapkmn.buscar(1);
                break;
            case 3:
                pk3 = listapkmn.buscar(1);
                break;
            case 4:
                pk4 = listapkmn.buscar(1);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }
    }//GEN-LAST:event_JBSquirtleActionPerformed

    private void JBSnorlaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSnorlaxActionPerformed
        // TODO add your handling code here:
        
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(3);
                break;
            case 2:
                pk2 = listapkmn.buscar(3);
                break;
            case 3:
                pk3 = listapkmn.buscar(3);
                break;
            case 4:
                pk4 = listapkmn.buscar(3);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }
        
    }//GEN-LAST:event_JBSnorlaxActionPerformed

    private void JBSlugmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSlugmaActionPerformed
        // TODO add your handling code here:
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(5);
                break;
            case 2:
                pk2 = listapkmn.buscar(5);
                break;
            case 3:
                pk3 = listapkmn.buscar(5);
                break;
            case 4:
                pk4 = listapkmn.buscar(5);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }
        
    }//GEN-LAST:event_JBSlugmaActionPerformed

    private void JBEeveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEeveeActionPerformed
        // TODO add your handling code here:
        
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(9);
                break;
            case 2:
                pk2 = listapkmn.buscar(9);
                break;
            case 3:
                pk3 = listapkmn.buscar(9);
                break;
            case 4:
                pk4 = listapkmn.buscar(9);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }
        
    }//GEN-LAST:event_JBEeveeActionPerformed

    private void JBArcanineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBArcanineActionPerformed
        // TODO add your handling code here:
        
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(8);
                break;
            case 2:
                pk2 = listapkmn.buscar(8);
                break;
            case 3:
                pk3 = listapkmn.buscar(8);
                break;
            case 4:
                pk4 = listapkmn.buscar(8);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }

        
    }//GEN-LAST:event_JBArcanineActionPerformed

    private void JBMagikarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMagikarpActionPerformed
        // TODO add your handling code here:
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(4);
                break;
            case 2:
                pk2 = listapkmn.buscar(4);
                break;
            case 3:
                pk3 = listapkmn.buscar(4);
                break;
            case 4:
                pk4 = listapkmn.buscar(4);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }

        
    }//GEN-LAST:event_JBMagikarpActionPerformed

    private void MeowthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeowthActionPerformed
        // TODO add your handling code here:
        
        contador++;
        
        switch(contador){
            case 1:
                pk1 = listapkmn.buscar(6);
                break;
            case 2:
                pk2 = listapkmn.buscar(6);
                break;
            case 3:
                pk3 = listapkmn.buscar(6);
                break;
            case 4:
                pk4 = listapkmn.buscar(6);
                break;
            default:
                JLWarning.setText("No se pueden agregar más de 4 Pokémon!");
        }

        
    }//GEN-LAST:event_MeowthActionPerformed

    private void JBStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBStartActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainBattle battle = new MainBattle();
        battle.JPPokemon.setVisible(false);
        battle.show();
        
    }//GEN-LAST:event_JBStartActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBArcanine;
    private javax.swing.JButton JBCharmander;
    private javax.swing.JButton JBEevee;
    private javax.swing.JButton JBLapras;
    private javax.swing.JButton JBMagikarp;
    private javax.swing.JButton JBSlugma;
    private javax.swing.JButton JBSnorlax;
    private javax.swing.JButton JBSquirtle;
    private javax.swing.JButton JBStart;
    private javax.swing.JLabel JLTitle;
    private javax.swing.JLabel JLWarning;
    private javax.swing.JButton Meowth;
    // End of variables declaration//GEN-END:variables
public class ImagenFondo extends JPanel{
     
    public void paint(Graphics g){
        ImageIcon imagen = new ImageIcon(getClass().getResource("FondoMenu.jpeg"));
        g.drawImage(imagen.getImage(),0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}

}
